version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend:/usr/src/app:cached
      - node_modules_volume:/usr/src/app/node_modules
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    tty: true

volumes:
  node_modules_volume:
