version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend:/usr/src/app:cached
      - node_modules_volume:/usr/src/app/node_modules
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    tty: true

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  backend:
    build:
      context: ./
      dockerfile: ./docker/ruby/Dockerfile
    volumes:
      - ./backend:/rails-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"

volumes:
  node_modules_volume:
